name: assignment_01_cipherschools
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0-257.0.dev <4.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  antdesign_icons: ^0.0.3
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  provider: ^6.0.5
  restart_app: ^1.1.2
  shared_preferences: ^2.1.0
  switcher_button: ^0.0.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
